In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
df = pd.read_csv(r'C:\Users\Lenovo\Desktop\NLP_Learning\IMDB Dataset.csv')

In [3]:
df.shape

(50000, 2)

In [4]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [5]:
df['review'][3].lower()

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.<br /><br />ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

In [6]:
df['review'] = df['review'].str.lower()

In [7]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. <br /><br />the...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

In [8]:
import re
def remove_html_tags(text):
    pattern = re.compile('<.*?>')
    return pattern.sub(r'', text)

In [9]:
text = "<html><body><p> Movie 1</p><p> Actor - Aamir Khan</p><p> Click here to <a href='http://google.com'>download</a></p></body></html>"

In [10]:
remove_html_tags(text)

' Movie 1 Actor - Aamir Khan Click here to download'

In [11]:
df['review'] = df['review'].apply(remove_html_tags)

In [12]:
df['review'][5]

'probably my all-time favorite movie, a story of selflessness, sacrifice and dedication to a noble cause, but it\'s not preachy or boring. it just never gets old, despite my having seen it some 15 or more times in the last 25 years. paul lukas\' performance brings tears to my eyes, and bette davis, in one of her very few truly sympathetic roles, is a delight. the kids are, as grandma says, more like "dressed-up midgets" than children, but that only makes them more fun to watch. and the mother\'s slow awakening to what\'s happening in the world and under her own roof is believable and startling. if i had a dozen thumbs, they\'d all be "up" for this movie.'

In [13]:
def remove_url(text):
    pattern = re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub(r'', text)

In [14]:
text1 = 'Check out my notebook https://www.kaggle.com/campusx/notebook8223fc1abb'
text2 = 'Check out my notebook http://www.kaggle.com/campusx/notebook8223fc1abb'
text3 = 'Google search here www.google.com'
text4 = 'For notebook click https://www.kaggle.com/campusx/notebook8223fc1abb to search check www.google.com'

In [16]:
remove_url(text4)

'For notebook click  to search check '

In [17]:
import string,time
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [18]:
exclude = string.punctuation

In [19]:
def remove_punc(text):
    for char in exclude:
        text = text.replace(char,'')
    return text

In [20]:
text = 'string. With. Punctuation?'

In [21]:
start = time.time()
print(remove_punc(text))
time1 = time.time() - start
print(time1*50000)

string With Punctuation
0.0

In [22]:
def remove_punc1(text):
    return text.translate(str.maketrans('', '', exclude))

In [23]:
start = time.time()
remove_punc1(text)
time2 = time.time() - start
print(time2*50000)

0.0

In [24]:
time1/time2

ZeroDivisionError: float division by zero

In [25]:
df['review'][5]

'probably my all-time favorite movie, a story of selflessness, sacrifice and dedication to a noble cause, but it\'s not preachy or boring. it just never gets old, despite my having seen it some 15 or more times in the last 25 years. paul lukas\' performance brings tears to my eyes, and bette davis, in one of her very few truly sympathetic roles, is a delight. the kids are, as grandma says, more like "dressed-up midgets" than children, but that only makes them more fun to watch. and the mother\'s slow awakening to what\'s happening in the world and under her own roof is believable and startling. if i had a dozen thumbs, they\'d all be "up" for this movie.'

In [26]:
remove_punc1(df['review'][5])

'probably my alltime favorite movie a story of selflessness sacrifice and dedication to a noble cause but its not preachy or boring it just never gets old despite my having seen it some 15 or more times in the last 25 years paul lukas performance brings tears to my eyes and bette davis in one of her very few truly sympathetic roles is a delight the kids are as grandma says more like dressedup midgets than children but that only makes them more fun to watch and the mothers slow awakening to whats happening in the world and under her own roof is believable and startling if i had a dozen thumbs theyd all be up for this movie'

In [35]:
chat_words = {
    'AFAIK': 'As Far As I Know',
    'AFK': 'Away From Keyboard',
    'ASAP': 'As Soon As Possible',
    'ATK': 'At The Keyboard',
    'ATM': 'At The Moment',
    'A3': 'Anytime, Anywhere, Anyplace',
    'BAK': 'Back At Keyboard',
    'BBL': 'Be Back Later',
    'BBS': 'Be Back Soon',
    'BFN': 'Bye For Now',
    'B4N': 'Bye For Now',
    'BRB': 'Be Right Back',
    'BRT': 'Be Right There',
    'BTW': 'By The Way',
    'B4': 'Before',
    'CU': 'See You',
    'CUL8R': 'See You Later',
    'CYA': 'See You',
    'FAQ': 'Frequently Asked Questions',
    'FC': 'Fingers Crossed',
    'FWIW': "For What It's Worth",
    'FYI': 'For Your Information',
    'GAL': 'Get A Life',
    'GG': 'Good Game',
    'GN': 'Good Night',
    'GMTA': 'Great Minds Think Alike',
    'GR8': 'Great!',
    'G9': 'Genius',
    'IC': 'I See',
    'ICQ': 'I Seek you (also a chat program)',
    'ILU': 'ILU: I Love You',
    'IMHO': 'In My Honest/Humble Opinion',
    'IMO': 'In My Opinion',
    'IOW': 'In Other Words',
    'IRL': 'In Real Life',
    'KISS': 'Keep It Simple, Stupid',
    'LDR': 'Long Distance Relationship',
    'LMAO': 'Laugh My A.. Off',
    'LOL': 'Laughing Out Loud',
    'LTNS': 'Long Time No See',
    'L8R': 'Later',
    'MTE': 'My Thoughts Exactly',
    'MB': 'Mate',
    'NRN': 'No Reply Necessary',
    'OIC': 'Oh I See',
    'PITA': 'Pain In The A..',
    'PRT': 'Party',
    'PRW': 'Parents Are Watching',
    'ROFL': 'Rolling On The Floor Laughing',
    'ROFLOL': 'Rolling On The Floor Laughing Out Loud',
    'ROTFLMAO': 'Rolling On The Floor Laughing My A.. Off',
    'SK8': 'Skate',
    'STATS': 'Your sex and age',
    'ASL': 'Age, Sex, Location',
    'THX': 'Thank You',
    'TTFN': 'Ta-Ta For Now!',
    'TTYL': 'Talk To You Later',
    'U': 'You',
    'U2': 'You Too',
    'U4E': 'Yours For Ever',
    'WB': 'Welcome Back',
    'WTF': 'What The F...',
    'WTG': 'Way To Go!',
    'WUF': 'Where Are You From?',
    'W8': 'Wait...',
    '7K': 'Sick:-D Laughter',
}

In [38]:
chat_words

{'AFAIK': 'As Far As I Know',
 'AFK': 'Away From Keyboard',
 'ASAP': 'As Soon As Possible',
 'ATK': 'At The Keyboard',
 'ATM': 'At The Moment',
 'A3': 'Anytime, Anywhere, Anyplace',
 'BAK': 'Back At Keyboard',
 'BBL': 'Be Back Later',
 'BBS': 'Be Back Soon',
 'BFN': 'Bye For Now',
 'B4N': 'Bye For Now',
 'BRB': 'Be Right Back',
 'BRT': 'Be Right There',
 'BTW': 'By The Way',
 'B4': 'Before',
 'CU': 'See You',
 'CUL8R': 'See You Later',
 'CYA': 'See You',
 'FAQ': 'Frequently Asked Questions',
 'FC': 'Fingers Crossed',
 'FWIW': "For What It's Worth",
 'FYI': 'For Your Information',
 'GAL': 'Get A Life',
 'GG': 'Good Game',
 'GN': 'Good Night',
 'GMTA': 'Great Minds Think Alike',
 'GR8': 'Great!',
 'G9': 'Genius',
 'IC': 'I See',
 'ICQ': 'I Seek you (also a chat program)',
 'ILU': 'ILU: I Love You',
 'IMHO': 'In My Honest/Humble Opinion',
 'IMO': 'In My Opinion',
 'IOW': 'In Other Words',
 'IRL': 'In Real Life',
 'KISS': 'Keep It Simple, Stupid',
 'LDR': 'Long Distance Relationship',
 'LMAO': 'Laugh My A.. Off',
 'LOL': 'Laughing Out Loud',
 'LTNS': 'Long Time No See',
 'L8R': 'Later',
 'MTE': 'My Thoughts Exactly',
 'MB': 'Mate',
 'NRN': 'No Reply Necessary',
 'OIC': 'Oh I See',
 'PITA': 'Pain In The A..',
 'PRT': 'Party',
 'PRW': 'Parents Are Watching',
 'ROFL': 'Rolling On The Floor Laughing',
 'ROFLOL': 'Rolling On The Floor Laughing Out Loud',
 'ROTFLMAO': 'Rolling On The Floor Laughing My A.. Off',
 'SK8': 'Skate',
 'STATS': 'Your sex and age',
 'ASL': 'Age, Sex, Location',
 'THX': 'Thank You',
 'TTFN': 'Ta-Ta For Now!',
 'TTYL': 'Talk To You Later',
 'U': 'You',
 'U2': 'You Too',
 'U4E': 'Yours For Ever',
 'WB': 'Welcome Back',
 'WTF': 'What The F...',
 'WTG': 'Way To Go!',
 'WUF': 'Where Are You From?',
 'W8': 'Wait...',
 '7K': 'Sick:-D Laughter'}

In [39]:
def chat_conversion(text):
    new_text = []
    for w in text.split():
        if w.upper() in chat_words:
            new_text.append(chat_words[w.upper()])
        else:
            new_text.append(w)
    return " ".join(new_text)

In [40]:
chat_conversion('IMHO he is the best')

'In My Honest/Humble Opinion he is the best'

In [41]:
chat_words

{'AFAIK': 'As Far As I Know',
 'AFK': 'Away From Keyboard',
 'ASAP': 'As Soon As Possible',
 'ATK': 'At The Keyboard',
 'ATM': 'At The Moment',
 'A3': 'Anytime, Anywhere, Anyplace',
 'BAK': 'Back At Keyboard',
 'BBL': 'Be Back Later',
 'BBS': 'Be Back Soon',
 'BFN': 'Bye For Now',
 'B4N': 'Bye For Now',
 'BRB': 'Be Right Back',
 'BRT': 'Be Right There',
 'BTW': 'By The Way',
 'B4': 'Before',
 'CU': 'See You',
 'CUL8R': 'See You Later',
 'CYA': 'See You',
 'FAQ': 'Frequently Asked Questions',
 'FC': 'Fingers Crossed',
 'FWIW': "For What It's Worth",
 'FYI': 'For Your Information',
 'GAL': 'Get A Life',
 'GG': 'Good Game',
 'GN': 'Good Night',
 'GMTA': 'Great Minds Think Alike',
 'GR8': 'Great!',
 'G9': 'Genius',
 'IC': 'I See',
 'ICQ': 'I Seek you (also a chat program)',
 'ILU': 'ILU: I Love You',
 'IMHO': 'In My Honest/Humble Opinion',
 'IMO': 'In My Opinion',
 'IOW': 'In Other Words',
 'IRL': 'In Real Life',
 'KISS': 'Keep It Simple, Stupid',
 'LDR': 'Long Distance Relationship',
 'LMAO': 'Laugh My A.. Off',
 'LOL': 'Laughing Out Loud',
 'LTNS': 'Long Time No See',
 'L8R': 'Later',
 'MTE': 'My Thoughts Exactly',
 'MB': 'Mate',
 'NRN': 'No Reply Necessary',
 'OIC': 'Oh I See',
 'PITA': 'Pain In The A..',
 'PRT': 'Party',
 'PRW': 'Parents Are Watching',
 'ROFL': 'Rolling On The Floor Laughing',
 'ROFLOL': 'Rolling On The Floor Laughing Out Loud',
 'ROTFLMAO': 'Rolling On The Floor Laughing My A.. Off',
 'SK8': 'Skate',
 'STATS': 'Your sex and age',
 'ASL': 'Age, Sex, Location',
 'THX': 'Thank You',
 'TTFN': 'Ta-Ta For Now!',
 'TTYL': 'Talk To You Later',
 'U': 'You',
 'U2': 'You Too',
 'U4E': 'Yours For Ever',
 'WB': 'Welcome Back',
 'WTF': 'What The F...',
 'WTG': 'Way To Go!',
 'WUF': 'Where Are You From?',
 'W8': 'Wait...',
 '7K': 'Sick:-D Laughter'}

In [42]:
chat_conversion('FYI delhi is the capital of india')

'For Your Information delhi is the capital of india'

In [43]:
pip install textblob

Collecting textblob
  Downloading textblob-0.20.1-py3-none-any.whl.metadata (4.0 kB)
Collecting nltk>=3.9 (from textblob)
  Downloading nltk-3.10.1-py3-none-any.whl.metadata (3.2 kB)
Collecting defusedxml (from nltk>=3.9->textblob)
  Using cached defusedxml-0.7.1-py2.py3-none-any.whl.metadata (32 kB)
Collecting click (from nltk>=3.9->textblob)
  Using cached click-8.4.2-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: joblib in e:\sign_train_first\myenv\lib\site-packages (from nltk>=3.9->textblob) (1.5.3)
Collecting regex>=2021.8.3 (from nltk>=3.9->textblob)
  Using cached regex-2026.7.19-cp311-cp311-win_amd64.whl.metadata (41 kB)
Requirement already satisfied: tqdm in e:\sign_train_first\myenv\lib\site-packages (from nltk>=3.9->textblob) (4.68.4)
Requirement already satisfied: colorama in e:\sign_train_first\myenv\lib\site-packages (from click->nltk>=3.9->textblob) (0.4.6)
Downloading textblob-0.20.1-py3-none-any.whl (624 kB)
   ---------------------------------------- 0.0/625.0 kB ? eta -:--:--
   - -------------------------------------- 30.7/625.0 kB ? eta -:--:--
   - -------------------------------------- 30.7/625.0 kB ? eta -:--:--
   ----- --------------------------------- 92.2/625.0 kB 751.6 kB/s eta 0:00:01
   ----- --------------------------------- 92.2/625.0 kB 751.6 kB/s eta 0:00:01
   ----- --------------------------------- 92.2/625.0 kB 751.6 kB/s eta 0:00:01
   ----- --------------------------------- 92.2/625.0 kB 751.6 kB/s eta 0:00:01
   ----- --------------------------------- 92.2/625.0 kB 751.6 kB/s eta 0:00:01
   ----- --------------------------------- 92.2/625.0 kB 751.6 kB/s eta 0:00:01
   ---------- --------------------------- 174.1/625.0 kB 403.5 kB/s eta 0:00:02
   ------------ ------------------------- 204.8/625.0 kB 461.0 kB/s eta 0:00:01
   ------------------ ------------------- 307.2/625.0 kB 613.6 kB/s eta 0:00:01
   --------------------- ---------------- 348.2/625.0 kB 636.4 kB/s eta 0:00:01
   -------------------------- ----------- 430.1/625.0 kB 747.0 kB/s eta 0:00:01
   ---------------------------------- --- 563.2/625.0 kB 908.0 kB/s eta 0:00:01
   -------------------------------------- 625.0/625.0 kB 959.0 kB/s eta 0:00:00
Downloading nltk-3.10.1-py3-none-any.whl (1.7 MB)
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
    --------------------------------------- 0.0/1.7 MB 1.9 MB/s eta 0:00:01
    --------------------------------------- 0.0/1.7 MB 1.9 MB/s eta 0:00:01
   ---- ----------------------------------- 0.2/1.7 MB 1.3 MB/s eta 0:00:02
   ---- ----------------------------------- 0.2/1.7 MB 1.4 MB/s eta 0:00:02
   ---- ----------------------------------- 0.2/1.7 MB 1.4 MB/s eta 0:00:02
   ------ --------------------------------- 0.3/1.7 MB 1.0 MB/s eta 0:00:02
   -------- ------------------------------- 0.4/1.7 MB 1.1 MB/s eta 0:00:02
   ---------- ----------------------------- 0.5/1.7 MB 1.3 MB/s eta 0:00:01
   ------------ --------------------------- 0.5/1.7 MB 1.5 MB/s eta 0:00:01
   --------------- ------------------------ 0.7/1.7 MB 1.4 MB/s eta 0:00:01
   ------------------ --------------------- 0.8/1.7 MB 1.6 MB/s eta 0:00:01
   --------------------- ------------------ 0.9/1.7 MB 1.6 MB/s eta 0:00:01
   ------------------------ --------------- 1.0/1.7 MB 1.7 MB/s eta 0:00:01
   ------------------------ --------------- 1.1/1.7 MB 1.8 MB/s eta 0:00:01
   ------------------------ --------------- 1.1/1.7 MB 1.8 MB/s eta 0:00:01
   ------------------------- -------------- 1.1/1.7 MB 1.5 MB/s eta 0:00:01
   -------------------------- ------------- 1.2/1.7 MB 1.6 MB/s eta 0:00:01
   ------------------------------ --------- 1.3/1.7 MB 1.6 MB/s eta 0:00:01
   ------------------------------- -------- 1.4/1.7 MB 1.6 MB/s eta 0:00:01
   --------------------------------- ------ 1.5/1.7 MB 1.6 MB/s eta 0:00:01
   ----------------------------------- ---- 1.5/1.7 MB 1.6 MB/s eta 0:00:01
   ------------------------------------ --- 1.6/1.7 MB 1.6 MB/s eta 0:00:01
   ------------------------------------ --- 1.6/1.7 MB 1.6 MB/s eta 0:00:01
   ------------------------------------ --- 1.6/1.7 MB 1.6 MB/s eta 0:00:01
   ------------------------------------ --- 1.6/1.7 MB 1.6 MB/s eta 0:00:01
   ------------------------------------ --- 1.6/1.7 MB 1.6 MB/s eta 0:00:01
   ---------------------------------------  1.7/1.7 MB 1.4 MB/s eta 0:00:01
   ---------------------------------------- 1.7/1.7 MB 1.4 MB/s eta 0:00:00
Using cached regex-2026.7.19-cp311-cp311-win_amd64.whl (277 kB)
Using cached click-8.4.2-py3-none-any.whl (119 kB)
Using cached defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
Installing collected packages: regex, defusedxml, click, nltk, textblob
Successfully installed click-8.4.2 defusedxml-0.7.1 nltk-3.10.1 regex-2026.7.19 textblob-0.20.1
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [44]:
from textblob import TextBlob

In [45]:
incorrect_text = 'ceertain conditionas duriing seveal ggenerations aree moodified in the saame maner.'

textBlb = TextBlob(incorrect_text)

textBlb.correct().string

'certain conditions during several generations are modified in the same manner.'

In [55]:
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [56]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [57]:
def remove_stopwords(text):
    new_text = []
    
    for word in text.split():
        if word in stopwords.words('english'):
            new_text.append('')
        else:
            new_text.append(word)
    x = new_text[:]
    new_text.clear()
    return " ".join(x)

In [58]:
remove_stopwords('probably my all-time favorite movie, a story of selflessness, sacrifice and dedication to a noble cause, but it\'s not preachy or boring. it just never gets old, despite my having seen it some 15 or more times')

'probably  all-time favorite movie,  story  selflessness, sacrifice  dedication   noble cause,    preachy  boring.   never gets old, despite   seen   15   times'

In [60]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. the filming tec...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

In [61]:
df['review'].apply(remove_stopwords)

0        one    reviewers  mentioned   watching  1 oz e...
1         wonderful little production.  filming techniq...
2         thought    wonderful way  spend time    hot s...
3        basically there's  family   little boy (jake) ...
4        petter mattei's "love   time  money"   visuall...
                               ...
49995     thought  movie    right good job.    creative...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997       catholic taught  parochial elementary schoo...
49998     going    disagree   previous comment  side  m...
49999     one expects  star trek movies   high art,   f...
Name: review, Length: 50000, dtype: str

In [63]:
import re
def remove_emoji(text):
    emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"  # emoticons
                           u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                           u"\U0001F680-\U0001F6FF"  # transport & map symbols
                           u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                           u"\U00002702-\U000027B0"
                           u"\U000024C2-\U0001F251"
                           "]+", flags=re.UNICODE)
    return emoji_pattern.sub(r'', text)

In [64]:
remove_emoji("Loved the movie. It was 😘😘")

'Loved the movie. It was '

In [65]:
remove_emoji("Lmao 😂😂")

'Lmao '

In [67]:
pip install emoji

Collecting emoji
  Downloading emoji-2.15.0-py3-none-any.whl.metadata (5.7 kB)
Downloading emoji-2.15.0-py3-none-any.whl (608 kB)
   ---------------------------------------- 0.0/608.4 kB ? eta -:--:--
    --------------------------------------- 10.2/608.4 kB ? eta -:--:--
   ---- ----------------------------------- 61.4/608.4 kB 1.1 MB/s eta 0:00:01
   ----------- ---------------------------- 174.1/608.4 kB 1.5 MB/s eta 0:00:01
   ----------------------------- ---------- 450.6/608.4 kB 3.1 MB/s eta 0:00:01
   ---------------------------------------- 608.4/608.4 kB 3.2 MB/s eta 0:00:00
Installing collected packages: emoji
Successfully installed emoji-2.15.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [68]:
import emoji
print(emoji.demojize('Python is 🔥'))

Python is :fire:

In [69]:
print(emoji.demojize('Loved the movie. It was 😘'))

Loved the movie. It was :face_blowing_a_kiss:

### 1. Using the split function

In [70]:
# word tokenization
sent1 = 'I am going to delhi'
sent1.split()

['I', 'am', 'going', 'to', 'delhi']

In [71]:
# sentence tokenization
sent2 = 'I am going to delhi. I will stay there for 3 days. Let\'s hope the trip to be great'
sent2.split('.')

['I am going to delhi',
 ' I will stay there for 3 days',
 " Let's hope the trip to be great"]

In [72]:
# Problems with split function
sent3 = 'I am going to delhi!'
sent3.split()

['I', 'am', 'going', 'to', 'delhi!']

In [73]:
sent4 = 'Where do think I should go? I have 3 day holiday'
sent4.split('.')

['Where do think I should go? I have 3 day holiday']

### 2. Regular Expression

In [74]:
import re
sent3 = 'I am going to delhi!'
tokens = re.findall("[\w']+", sent3)
tokens

['I', 'am', 'going', 'to', 'delhi']

In [75]:

text = """Lorem Ipsum is simply dummy text of the printing and typesetting industry? 
Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, 
when an unknown printer took a galley of type and scrambled it to make a type specimen book."""
sentences = re.compile('[.!?] ').split(text)
sentences

['Lorem Ipsum is simply dummy text of the printing and typesetting industry',
 "\nLorem Ipsum has been the industry's standard dummy text ever since the 1500s, \nwhen an unknown printer took a galley of type and scrambled it to make a type specimen book."]

### 3. NLTK

In [5]:
from nltk.tokenize import word_tokenize,sent_tokenize

In [6]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [7]:
sent1 = 'I am going to visit delhi!'
word_tokenize(sent1)

['I', 'am', 'going', 'to', 'visit', 'delhi', '!']

In [8]:
text = """Lorem Ipsum is simply dummy text of the printing and typesetting industry? 
Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, 
when an unknown printer took a galley of type and scrambled it to make a type specimen book."""

sent_tokenize(text)

['Lorem Ipsum is simply dummy text of the printing and typesetting industry?',
 "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, \nwhen an unknown printer took a galley of type and scrambled it to make a type specimen book."]

In [9]:
sent5 = 'I have a Ph.D in A.I'
sent6 = "We're here to help! mail us at nks@gmail.com"
sent7 = 'A 5km ride cost $10.50'

word_tokenize(sent5)

['I', 'have', 'a', 'Ph.D', 'in', 'A.I']

In [84]:
word_tokenize(sent6)

['We',
 "'re",
 'here',
 'to',
 'help',
 '!',
 'mail',
 'us',
 'at',
 'nks',
 '@',
 'gmail.com']

In [85]:
word_tokenize(sent7)

['A', '5km', 'ride', 'cost', '$', '10.50']

In [87]:
pip install spacy

Collecting spacy
  Downloading spacy-3.8.14-cp311-cp311-win_amd64.whl.metadata (28 kB)
Collecting spacy-legacy<3.1.0,>=3.0.11 (from spacy)
  Downloading spacy_legacy-3.0.12-py2.py3-none-any.whl.metadata (2.8 kB)
Collecting spacy-loggers<2.0.0,>=1.0.0 (from spacy)
  Downloading spacy_loggers-1.0.5-py3-none-any.whl.metadata (23 kB)
Collecting murmurhash<1.1.0,>=0.28.0 (from spacy)
  Downloading murmurhash-1.0.15-cp311-cp311-win_amd64.whl.metadata (2.3 kB)
Collecting cymem<2.1.0,>=2.0.2 (from spacy)
  Downloading cymem-2.0.13-cp311-cp311-win_amd64.whl.metadata (9.9 kB)
Collecting preshed<3.1.0,>=3.0.2 (from spacy)
  Downloading preshed-3.0.13-cp311-cp311-win_amd64.whl.metadata (5.4 kB)
Collecting thinc<8.4.0,>=8.3.12 (from spacy)
  Downloading thinc-8.3.13-cp311-cp311-win_amd64.whl.metadata (15 kB)
Collecting wasabi<1.2.0,>=0.9.1 (from spacy)
  Downloading wasabi-1.1.3-py3-none-any.whl.metadata (28 kB)
Collecting srsly<3.0.0,>=2.5.3 (from spacy)
  Downloading srsly-2.5.3-cp311-cp311-win_amd64.whl.metadata (20 kB)
Collecting catalogue<2.1.0,>=2.0.6 (from spacy)
  Downloading catalogue-2.0.10-py3-none-any.whl.metadata (14 kB)
Collecting weasel<2.0.0,>=1.0.0 (from spacy)
  Downloading weasel-1.0.0-py3-none-any.whl.metadata (4.6 kB)
Collecting confection<2.0.0,>=1.3.2 (from spacy)
  Downloading confection-1.3.3-py3-none-any.whl.metadata (19 kB)
Collecting typer<1.0.0,>=0.3.0 (from spacy)
  Downloading typer-0.27.1-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in e:\sign_train_first\myenv\lib\site-packages (from spacy) (4.68.4)
Requirement already satisfied: numpy>=1.19.0 in e:\sign_train_first\myenv\lib\site-packages (from spacy) (2.4.6)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in e:\sign_train_first\myenv\lib\site-packages (from spacy) (2.34.2)
Collecting pydantic<3.0.0,>=2.0.0 (from spacy)
  Using cached pydantic-2.13.4-py3-none-any.whl.metadata (109 kB)
Requirement already satisfied: jinja2 in e:\sign_train_first\myenv\lib\site-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in e:\sign_train_first\myenv\lib\site-packages (from spacy) (65.5.0)
Requirement already satisfied: packaging>=20.0 in e:\sign_train_first\myenv\lib\site-packages (from spacy) (26.2)
Collecting annotated-types>=0.6.0 (from pydantic<3.0.0,>=2.0.0->spacy)
  Downloading annotated_types-0.8.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.46.4 (from pydantic<3.0.0,>=2.0.0->spacy)
  Using cached pydantic_core-2.46.4-cp311-cp311-win_amd64.whl.metadata (6.7 kB)
Requirement already satisfied: typing-extensions>=4.14.1 in e:\sign_train_first\myenv\lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (4.16.0)
Collecting typing-inspection>=0.4.2 (from pydantic<3.0.0,>=2.0.0->spacy)
  Using cached typing_inspection-0.4.2-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in e:\sign_train_first\myenv\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in e:\sign_train_first\myenv\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in e:\sign_train_first\myenv\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in e:\sign_train_first\myenv\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.6.17)
Collecting blis<1.4.0,>=1.3.0 (from thinc<8.4.0,>=8.3.12->spacy)
  Downloading blis-1.3.3-cp311-cp311-win_amd64.whl.metadata (7.7 kB)
Requirement already satisfied: colorama in e:\sign_train_first\myenv\lib\site-packages (from tqdm<5.0.0,>=4.38.0->spacy) (0.4.6)
Collecting shellingham>=1.3.0 (from typer<1.0.0,>=0.3.0->spacy)
  Using cached shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting rich>=13.8.0 (from typer<1.0.0,>=0.3.0->spacy)
  Using cached rich-15.0.0-py3-none-any.whl.metadata (18 kB)
Collecting annotated-doc>=0.0.2 (from typer<1.0.0,>=0.3.0->spacy)
  Downloading annotated_doc-0.0.5-py3-none-any.whl.metadata (6.5 kB)
Collecting cloudpathlib>=0.7.0 (from weasel<2.0.0,>=1.0.0->spacy)
  Downloading cloudpathlib-0.24.0-py3-none-any.whl.metadata (16 kB)
Collecting smart-open>=5.2.1 (from weasel<2.0.0,>=1.0.0->spacy)
  Downloading smart_open-8.0.1-py3-none-any.whl.metadata (24 kB)
Collecting httpx>=0.24.0 (from weasel<2.0.0,>=1.0.0->spacy)
  Using cached httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: MarkupSafe>=2.0 in e:\sign_train_first\myenv\lib\site-packages (from jinja2->spacy) (3.0.3)
Collecting anyio (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy)
  Using cached anyio-4.14.2-py3-none-any.whl.metadata (4.6 kB)
Collecting httpcore==1.* (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy)
  Using cached httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Collecting h11>=0.16 (from httpcore==1.*->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy)
  Using cached h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Collecting markdown-it-py>=2.2.0 (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy)
  Using cached markdown_it_py-4.2.0-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in e:\sign_train_first\myenv\lib\site-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (2.20.0)
Collecting wrapt (from smart-open>=5.2.1->weasel<2.0.0,>=1.0.0->spacy)
  Downloading wrapt-2.3.0-cp311-cp311-win_amd64.whl.metadata (7.6 kB)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Downloading spacy-3.8.14-cp311-cp311-win_amd64.whl (15.4 MB)
   ---------------------------------------- 0.0/15.4 MB ? eta -:--:--
   ---------------------------------------- 0.1/15.4 MB 1.7 MB/s eta 0:00:10
    --------------------------------------- 0.2/15.4 MB 2.1 MB/s eta 0:00:08
   - -------------------------------------- 0.6/15.4 MB 4.4 MB/s eta 0:00:04
   --- ------------------------------------ 1.2/15.4 MB 6.8 MB/s eta 0:00:03
   ------ --------------------------------- 2.3/15.4 MB 10.6 MB/s eta 0:00:02
   --------- ------------------------------ 3.6/15.4 MB 13.6 MB/s eta 0:00:01
   ------------ --------------------------- 4.9/15.4 MB 15.8 MB/s eta 0:00:01
   ---------------- ----------------------- 6.2/15.4 MB 17.2 MB/s eta 0:00:01
   ------------------- -------------------- 7.4/15.4 MB 18.2 MB/s eta 0:00:01
   ---------------------- ----------------- 8.6/15.4 MB 18.9 MB/s eta 0:00:01
   ----------------------- ---------------- 8.9/15.4 MB 19.0 MB/s eta 0:00:01
   ----------------------- ---------------- 8.9/15.4 MB 19.0 MB/s eta 0:00:01
   --------------------------- ------------ 10.4/15.4 MB 20.5 MB/s eta 0:00:01
   ----------------------------- ---------- 11.4/15.4 MB 22.6 MB/s eta 0:00:01
   ---------------------------------- ----- 13.3/15.4 MB 23.4 MB/s eta 0:00:01
   ----------------------------------- ---- 13.5/15.4 MB 22.6 MB/s eta 0:00:01
   -------------------------------------- - 14.7/15.4 MB 21.8 MB/s eta 0:00:01
   -------------------------------------- - 14.7/15.4 MB 21.8 MB/s eta 0:00:01
   -------------------------------------- - 14.7/15.4 MB 21.8 MB/s eta 0:00:01
   -------------------------------------- - 14.8/15.4 MB 16.8 MB/s eta 0:00:01
   ---------------------------------------- 15.4/15.4 MB 16.4 MB/s eta 0:00:00
Downloading catalogue-2.0.10-py3-none-any.whl (17 kB)
Downloading confection-1.3.3-py3-none-any.whl (35 kB)
Downloading cymem-2.0.13-cp311-cp311-win_amd64.whl (40 kB)
   ---------------------------------------- 0.0/40.1 kB ? eta -:--:--
   ---------------------------------------- 40.1/40.1 kB 1.9 MB/s eta 0:00:00
Downloading murmurhash-1.0.15-cp311-cp311-win_amd64.whl (25 kB)
Downloading preshed-3.0.13-cp311-cp311-win_amd64.whl (122 kB)
   ---------------------------------------- 0.0/122.2 kB ? eta -:--:--
   ---------------------------------------- 122.2/122.2 kB 7.0 MB/s eta 0:00:00
Using cached pydantic-2.13.4-py3-none-any.whl (472 kB)
Using cached pydantic_core-2.46.4-cp311-cp311-win_amd64.whl (2.1 MB)
Downloading spacy_legacy-3.0.12-py2.py3-none-any.whl (29 kB)
Downloading spacy_loggers-1.0.5-py3-none-any.whl (22 kB)
Downloading srsly-2.5.3-cp311-cp311-win_amd64.whl (651 kB)
   ---------------------------------------- 0.0/651.7 kB ? eta -:--:--
   --------------------------------------- 651.7/651.7 kB 40.1 MB/s eta 0:00:00
Downloading thinc-8.3.13-cp311-cp311-win_amd64.whl (1.8 MB)
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------- ----------------- 1.0/1.8 MB 32.7 MB/s eta 0:00:01
   ---------------------------------------  1.8/1.8 MB 22.8 MB/s eta 0:00:01
   ---------------------------------------- 1.8/1.8 MB 19.0 MB/s eta 0:00:00
Downloading typer-0.27.1-py3-none-any.whl (122 kB)
   ---------------------------------------- 0.0/122.9 kB ? eta -:--:--
   ---------------------------------------- 122.9/122.9 kB ? eta 0:00:00
Downloading wasabi-1.1.3-py3-none-any.whl (27 kB)
Downloading weasel-1.0.0-py3-none-any.whl (50 kB)
   ---------------------------------------- 0.0/50.7 kB ? eta -:--:--
   ---------------------------------------- 50.7/50.7 kB ? eta 0:00:00
Downloading annotated_doc-0.0.5-py3-none-any.whl (5.3 kB)
Downloading annotated_types-0.8.0-py3-none-any.whl (13 kB)
Downloading blis-1.3.3-cp311-cp311-win_amd64.whl (6.2 MB)
   ---------------------------------------- 0.0/6.2 MB ? eta -:--:--
   -------- ------------------------------- 1.3/6.2 MB 26.8 MB/s eta 0:00:01
   -------------- ------------------------- 2.2/6.2 MB 23.7 MB/s eta 0:00:01
   -------------------- ------------------- 3.2/6.2 MB 22.9 MB/s eta 0:00:01
   ---------------------------- ----------- 4.4/6.2 MB 23.1 MB/s eta 0:00:01
   ----------------------------------- ---- 5.4/6.2 MB 23.1 MB/s eta 0:00:01
   ---------------------------------------  6.2/6.2 MB 21.9 MB/s eta 0:00:01
   ---------------------------------------- 6.2/6.2 MB 21.9 MB/s eta 0:00:00
Downloading cloudpathlib-0.24.0-py3-none-any.whl (63 kB)
   ---------------------------------------- 0.0/63.2 kB ? eta -:--:--
   ---------------------------------------- 63.2/63.2 kB ? eta 0:00:00
Using cached httpx-0.28.1-py3-none-any.whl (73 kB)
Using cached httpcore-1.0.9-py3-none-any.whl (78 kB)
Using cached rich-15.0.0-py3-none-any.whl (310 kB)
Using cached shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Downloading smart_open-8.0.1-py3-none-any.whl (73 kB)
   ---------------------------------------- 0.0/73.5 kB ? eta -:--:--
   ---------------------------------------- 73.5/73.5 kB ? eta 0:00:00
Using cached typing_inspection-0.4.2-py3-none-any.whl (14 kB)
Using cached markdown_it_py-4.2.0-py3-none-any.whl (91 kB)
Using cached anyio-4.14.2-py3-none-any.whl (125 kB)
Downloading wrapt-2.3.0-cp311-cp311-win_amd64.whl (80 kB)
   ---------------------------------------- 0.0/80.9 kB ? eta -:--:--
   ---------------------------------------- 80.9/80.9 kB 4.4 MB/s eta 0:00:00
Using cached h11-0.16.0-py3-none-any.whl (37 kB)
Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Installing collected packages: wrapt, wasabi, typing-inspection, spacy-loggers, spacy-legacy, shellingham, pydantic-core, murmurhash, mdurl, h11, cymem, confection, cloudpathlib, catalogue, blis, anyio, annotated-types, annotated-doc, srsly, smart-open, pydantic, preshed, markdown-it-py, httpcore, thinc, rich, httpx, typer, weasel, spacy
Successfully installed annotated-doc-0.0.5 annotated-types-0.8.0 anyio-4.14.2 blis-1.3.3 catalogue-2.0.10 cloudpathlib-0.24.0 confection-1.3.3 cymem-2.0.13 h11-0.16.0 httpcore-1.0.9 httpx-0.28.1 markdown-it-py-4.2.0 mdurl-0.1.2 murmurhash-1.0.15 preshed-3.0.13 pydantic-2.13.4 pydantic-core-2.46.4 rich-15.0.0 shellingham-1.5.4 smart-open-8.0.1 spacy-3.8.14 spacy-legacy-3.0.12 spacy-loggers-1.0.5 srsly-2.5.3 thinc-8.3.13 typer-0.27.1 typing-inspection-0.4.2 wasabi-1.1.3 weasel-1.0.0 wrapt-2.3.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
!python -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
     ---------------------------------------- 0.1/12.8 MB 1.3 MB/s eta 0:00:10
      --------------------------------------- 0.2/12.8 MB 2.0 MB/s eta 0:00:07
     - -------------------------------------- 0.5/12.8 MB 3.0 MB/s eta 0:00:05
     ---- ----------------------------------- 1.3/12.8 MB 6.5 MB/s eta 0:00:02
     ------ --------------------------------- 2.2/12.8 MB 8.7 MB/s eta 0:00:02
     --------- ------------------------------ 3.2/12.8 MB 10.7 MB/s eta 0:00:01
     ------------ --------------------------- 4.1/12.8 MB 11.8 MB/s eta 0:00:01
     --------------- ------------------------ 4.9/12.8 MB 12.5 MB/s eta 0:00:01
     ------------------ --------------------- 5.9/12.8 MB 13.6 MB/s eta 0:00:01
     ---------------------- ----------------- 7.3/12.8 MB 15.0 MB/s eta 0:00:01
     -------------------------- ------------- 8.4/12.8 MB 15.8 MB/s eta 0:00:01
     ------------------------------ --------- 9.8/12.8 MB 16.9 MB/s eta 0:00:01
     -------------------------------- ------ 10.7/12.8 MB 21.8 MB/s eta 0:00:01
     --------------------------------- ----- 11.0/12.8 MB 21.9 MB/s eta 0:00:01
     ----------------------------------- --- 11.7/12.8 MB 20.5 MB/s eta 0:00:01
     --------------------------------------- 12.8/12.8 MB 20.5 MB/s eta 0:00:00
Installing collected packages: en-core-web-sm
Successfully installed en-core-web-sm-3.8.0
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

### 4. Spacy

In [1]:
import spacy
nlp = spacy.load('en_core_web_sm')

In [10]:
doc1 = nlp(sent5)
doc2 = nlp(sent6)
doc3 = nlp(sent7)
doc4 = nlp(sent1)

In [11]:
for token in doc4:
    print(token)

I
am
going
to
visit
delhi
!

In [12]:
from nltk.stem.porter import PorterStemmer

In [13]:
ps = PorterStemmer()
def stem_words(text):
    return " ".join([ps.stem(word) for word in text.split()])

In [14]:
sample = "walk walks walking walked"
stem_words(sample)

'walk walk walk walk'

In [15]:
text = 'probably my alltime favorite movie a story of selflessness sacrifice and dedication to a noble cause but its not preachy or boring it just never gets old despite my having seen it some 15 or more times in the last 25 years paul lukas performance brings tears to my eyes and bette davis in one of her very few truly sympathetic roles is a delight the kids are as grandma says more like dressedup midgets than children but that only makes them more fun to watch and the mothers slow awakening to whats happening in the world and under her own roof is believable and startling if i had a dozen thumbs theyd all be up for this movie'
print(text)

probably my alltime favorite movie a story of selflessness sacrifice and dedication to a noble cause but its not preachy or boring it just never gets old despite my having seen it some 15 or more times in the last 25 years paul lukas performance brings tears to my eyes and bette davis in one of her very few truly sympathetic roles is a delight the kids are as grandma says more like dressedup midgets than children but that only makes them more fun to watch and the mothers slow awakening to whats happening in the world and under her own roof is believable and startling if i had a dozen thumbs theyd all be up for this movie

In [16]:
stem_words(text)

'probabl my alltim favorit movi a stori of selfless sacrific and dedic to a nobl caus but it not preachi or bore it just never get old despit my have seen it some 15 or more time in the last 25 year paul luka perform bring tear to my eye and bett davi in one of her veri few truli sympathet role is a delight the kid are as grandma say more like dressedup midget than children but that onli make them more fun to watch and the mother slow awaken to what happen in the world and under her own roof is believ and startl if i had a dozen thumb theyd all be up for thi movi'

In [18]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...

True

In [19]:
import nltk
from nltk.stem import WordNetLemmatizer
wordnet_lemmatizer = WordNetLemmatizer()

sentence = "He was running and eating at same time. He has bad habit of swimming after playing long hours in the Sun."
punctuations="?:!.,;"
sentence_words = nltk.word_tokenize(sentence)
for word in sentence_words:
    if word in punctuations:
        sentence_words.remove(word)

sentence_words
print("{0:20}{1:20}".format("Word","Lemma"))
for word in sentence_words:
    print ("{0:20}{1:20}".format(word,wordnet_lemmatizer.lemmatize(word,pos='v')))

Word                Lemma
He                  He
was                 be
running             run
and                 and
eating              eat
at                  at
same                same
time                time
He                  He
has                 have
bad                 bad
habit               habit
of                  of
swimming            swim
after               after
playing             play
long                long
hours               hours
in                  in
the                 the
Sun                 Sun